stages:
  - build
  - publish


build game:
  stage: build
  script:
    - apt-get update && apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended python3 make
    - (cd Production && ../Extras/vgametex.py -- make)
    - (cd Greensheets && ../Extras/vgametex.py -- make)
    - ls -lR; pwd
    - mkdir artifacts artifacts/sheets artifacts/greensheets
    - cp Production/*.pdf Production/json-PRINT.json artifacts/sheets/
    - cp Greensheets/*.pdf artifacts/greensheets/

  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week

pages:
  # "pages" job name is special, and triggers creation of GitLab pages:
  # https://gitlab.com/help/user/project/pages/getting_started_part_four.md
  stage: publish
  script:
    - mkdir -p public
    - test -a public/index.html || echo "<p><a href='rules-scenario.pdf'>Rules &amp; Scenario</a></p>" > public/index.html
    - cp artifacts/sheets/rules-scenario.pdf public/

  artifacts:
    paths:
      - public
    expire_in: 1 month

  only:
    - master
